# Preparation for Creating Plots and ab-lines


## Read boundary and ab-line

```{r }
# ffy <- "Wendte_LaueLib80_2020"
# ffy <- "Boeckner_134n_2017"
# ffy <- "Bohnhoff_Adams_2018"
# ffy <- "Holzwart_Holzwart_2021"

#/*=================================================*/
#' # Field boundary
#/*=================================================*/
field_sf <- get_shp_name(ffy, "TrialDesign", "boundary") %>% 
  st_read() %>% 
  make_sf_utm() %>% 
  st_combine()

field_bbox <- st_bbox(field_sf) 
field_len_cross <- sqrt(
  (field_bbox["xmax"] - field_bbox["xmin"]) ^2 +
  (field_bbox["ymax"] - field_bbox["ymin"]) ^2 
)

#/*=================================================*/
#' # Plot-heading
#/*=================================================*/

#/*----------------------------------*/
#' ## Input ab-line
#/*----------------------------------*/
input_ab_line_files <- get_shp_name(
  ffy, "TrialDesign", 
  "ab-line-i|ab-line-n|ab-line-s|ab-line-k|
  ab-lines-i|ab-lines-n|ab-lines-s|ab-lines-k"
) 
past_input_files <- get_shp_name(ffy, "TrialDesign", "past-a-s|past-a-n|past-a-k") 

if (length(input_ab_line_files) > 0) {

  i_ab_line <- 
  input_ab_line_files[1] %>% 
  st_read() %>% 
  make_sf_utm() %>% 
  #=== use the first one if there are two ===#
  .[1,]

} else if (length(past_input_files) > 0) {

  i_ab_line <- 
  past_input_files[1] %>% 
  st_read() %>% 
  make_sf_utm() %>% 
  make_ab_line(field_sf)  
 
} else {

}

#=== make ab_line the width of the field ===#
i_ab_line <- 
st_extend_line(
  st_geometry(i_ab_line), 
  field_len_cross / as.numeric(st_length(i_ab_line))
)

#/*=================================================*/
#' # Harvester ab-line
#/*=================================================*/
#=== harvest angle ===#
harvest_angle <- _harvest-angle-here_

if (harvest_angle == TRUE) {

  harvester_ab_line_files <- get_shp_name(ffy, "TrialDesign", "ab-line-h") 
  past_harvester_files <- get_shp_name(ffy, "TrialDesign", "past-a-h") 

  if (length(harvester_ab_line_files) > 0) {
    #=== use only the first one ===#
    h_ab_line <- 
    harvester_ab_line_files[1] %>% 
    st_read() %>% 
    make_sf_utm() %>% 
    #=== use the first one if there are two ===#
    .[1,] 

  } else if (length(past_harvester_files) > 0) {

    h_ab_line <- 
    past_harvester_files[1] %>% 
    st_read() %>% 
    make_sf_utm() %>% 
    make_ab_line(field_sf) 

    # ggplot() +
    #   geom_sf(data = h_ab_line, size = 2) +
    #   geom_sf(data = h_ab_line_2, color = "red") 
  } else {

    cat("No ab-line for harvest data or past harvest data files are available.")

  }

  harvest_angle <- get_angle_lines(h_ab_line, i_ab_line)
    
} else {

  h_ab_line <- NULL

}

```

```{r }

if (length(h_ab_line) > 0) {
  #=== make ab_line the width of the field ===#
  h_ab_line <- 
  st_extend_line(
    st_geometry(h_ab_line), 
    field_len_cross / as.numeric(st_length(h_ab_line))
  )

  ab_lines_tmap <- c(i_ab_line, h_ab_line) %>% 
    st_as_sf() %>% 
    mutate(ab_id = c("input ab-line", "harvester ab-line"))

  ggplot() +
    geom_sf(data = field_sf) +
    geom_sf(data = ab_lines_tmap, aes(col = ab_id)) 

} else {

  ab_lines_tmap <- c(i_ab_line) %>% 
    st_as_sf() %>% 
    mutate(ab_id = "input ab-line")

  ggplot() +
    geom_sf(data = field_sf) +
    geom_sf(data = ab_lines_tmap, aes(col = ab_id))

}

```

## Option parameters

```{r }
#/*----------------------------------*/
#' ## Parameter
#/*----------------------------------*/
#=== head distance ===#
head_dist <- _head-dist-here_

if (is.na(head_dist)) {
  head_dist <- 2 * max(trial_data$machine_width)
} else {
  head_dist <- conv_unit(head_dist, "ft", "m")
}

#=== side distance ===#
side_dist <- _side-dist-here_ 

if (is.na(side_dist)) {
  side_dist <- max(max(trial_data$section_width), 30)
} else {
  side_dist <- conv_unit(side_dist, "ft", "m")
}

#=== lock_start_point ===#
lock_start_point <- readRDS(
  here("Data", "Growers", ffy, "TrialDesign/lock_start.rds")
)
if (nrow(trial_data) == 1) {
  lock_start_point <- lock_start_point[1]
}


#/*----------------------------------*/
#' ## Trial data 
#/*----------------------------------*/
trial_data_rh <- trial_data %>% 
  #=== headland length ===#
  # if only one number is supplied, it is applied for both inputs in a two-input case
  mutate(headland_length = head_dist) %>% 
  #=== side length ===#
  mutate(side_length = side_dist) %>% 
  #=== harvester angler ===#
  mutate(harvest_angle = harvest_angle) %>% 
  #=== lock start ===#
  mutate(lock_start = lock_start_point) %>% 
  #=== first create plots for the input where the starting point is locked ===#
  arrange(desc(lock_start))

```

# Create Trial Design

## Make experiment grids

```{r }

#/*----------------------------------*/
#' ## Create experimental plots
#/*----------------------------------*/

num_unique_plot_width <- 
unique(trial_data_rh$input_plot_width) %>% 
length()

#=== get the first one of the two if more than one ===#
# input_plot_width <- trial_data_first$input_plot_width[[1]]
# machine_width <- trial_data_first$machine_width[[1]]
# section_num <- trial_data_first$section_num[[1]]
# headland_length <- trial_data_first$headland_length[[1]]
# side_length <- trial_data_first$side_length[[1]]
# harvest_angle <- trial_data_first$harvest_angle[[1]]
# lock_start <- trial_data_first$lock_start[[1]]
# field = field_sf
# #--- by default uses the first one ---#
# ab_line = i_ab_line[1, ]
# plot_width = input_plot_width

trial_data_first <- 
trial_data_rh[1, ] %>% 
mutate(line_edge_id = NA) %>% 
rowwise() %>% 
mutate(experiment_plots = list(
  make_trial_grids(
    field = field_sf, 
    #--- by default uses the first one ---#
    ab_line = i_ab_line[1, ], 
    plot_width = input_plot_width, 
    machine_width = machine_width, 
    section_num = section_num, 
    headland_length = headland_length,
    side_length = side_length,
    harvest_angle = harvest_angle,
    lock_start = lock_start
  )
))

if (num_unique_plot_width == 1 & nrow(trial_data_rh) == 1) {

  trial_data_e <- trial_data_first 

} else if(num_unique_plot_width == 1 & nrow(trial_data_rh) == 2) {

  trial_data_second <- 
  trial_data_rh[2, ] %>% 
  mutate(experiment_plots = list(
    trial_data_first$experiment_plots[[1]]
  )) %>% 
  mutate(line_edge_id = NA)

  trial_data_e <- rbind(trial_data_first, trial_data_second)
  # trial_data_e$experiment_plots

} else {

  trial_data_second <- 
  trial_data_rh[2, ] %>% 
  slice(rep(1, 2)) %>% 
  mutate(line_edge_id = 1:2) %>% 
  rowwise() %>% 
  mutate(experiment_plots = list(
    make_trial_grids(
      field = field_sf, 
      #--- by default uses the first one ---#
      ab_line = trial_data_first$experiment_plots[[1]]$line_edges[line_edge_id, ], 
      plot_width = input_plot_width, 
      machine_width = machine_width,
      headland_length = headland_length,
      side_length = side_length,
      harvest_angle = harvest_angle,
      lock_start = FALSE,
      second_input = TRUE
    )   
  )) 

  trial_data_e <- rbind(trial_data_first, trial_data_second)

}

``` 

```{r }

trial_data_eh <-
trial_data_e %>% 
rowwise() %>% 
mutate(ab_lines = list(
  experiment_plots$ab_lines %>% 
    st_transform(4326)
)) %>% 
mutate(exp_plots = list(
  experiment_plots$exp_plots
)) %>% 
dplyr::select(- experiment_plots) %>% 
#=== dissolve the experimental plots as a single polygon ===#
mutate(experiment_plots_dissolved = list(
  exp_plots %>% 
    st_buffer(0.01) %>% # this avoids tiny tiny gaps between plots
    st_snap_to_grid(size = 0.0001) %>%
    st_make_valid() %>% 
    summarize(plot_id = min(plot_id)) 
)) %>% 
#=== Create headland ===#
# experiment_plots_dissolved <- trial_data_eh$experiment_plots_dissolved
# trial_data_eh$headland
mutate(headland = list(
  st_difference(field_sf, experiment_plots_dissolved) %>%
    st_as_sf() %>% 
    rename(., geometry = attr(., "sf_column")) %>% 
    dplyr::select(geometry)
)) %>% 
mutate(tm_exp_head = list(
  tm_shape(field_sf) +
    tm_borders(col = "black") + 
  tm_shape(headland) +
    tm_fill(
      col = "red", 
      alpha = 0.3, 
      title = "Headland"
    ) +
  tm_shape(exp_plots) +
    tm_fill(
      col = "strip_id", 
      palette = "Spectral", 
      style = "order"
    )  +
  tm_shape(field_sf) +
    tm_borders() +
  tm_layout_to_add 
))

```

```{r }
trial_data_eh$tm_exp_head

```

## Save experiment plots and headland

```{r }
saveRDS(
  trial_data_eh,
  here("Data", "Growers", ffy, "TrialDesign", "exp_plots.rds")
)  
```
